services:
  dev:
    build:
      context: .
      dockerfile: docker/go.dev.Dockerfile
    container_name: grpc-sample-server-dev

    working_dir: /app

    networks:
      - grpc_sample_network

    volumes:
      - .:/app
      - go-mod-cache:/go/pkg/mod

    ports:
      - "7000:7000"

    environment:
      - GRPC_PORT=7000
      - GOMODCACHE=/go/pkg/mod

volumes:
  go-mod-cache:

networks:
  grpc_sample_network:
    external: true
    name: grpc_sample_network
