name: Deploy To Server

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
      - feat/**
env:
  IMAGE_NAME: "grpc-sample-server-prod"
  IMAGE_VERSION: "latest"
  IMAGE_NAME_TAR: "grpc-sample-server-prod.tar"
  PATH_PROJECT: "/home/cutbray/grpc-sample-server"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Create network grpc_sample_network
        run: docker network create grpc_sample_network || echo "Network grpc_sample_network already exists"

      - name: Run docker compose development
        run: docker compose -f docker-compose.yml up -d

  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: "Build Docker Image"
        run: |
          IMAGE_NAME="${{ env.IMAGE_NAME }}" IMAGE_VERSION="${{ env.IMAGE_VERSION }}" docker compose -f docker-compose.prod.yml build grpc-sample-server-prod
          docker save ${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }} -o ${{ env.IMAGE_NAME_TAR }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.IMAGE_NAME }}
          path: |
            docker-compose.prod.yml
            ${{ env.IMAGE_NAME_TAR }}

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: [self-hosted, Linux, grpc-sample-server]

    steps:
      # - name: Checkout repository
      #   uses: actions/checkout@v5

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.IMAGE_NAME }}
          path: ${{ env.PATH_PROJECT }}

      - name: Load Docker Image
        run: |
          cd ${{ env.PATH_PROJECT }}
          docker load -i ${{ env.IMAGE_NAME_TAR }}

      - name: List Docker images
        run: docker image ls

      - name: Run Production App with Docker Compose
        run: |
          cd ${{ env.PATH_PROJECT }} && echo $(pwd)
          IMAGE_NAME="${{ env.IMAGE_NAME }}" IMAGE_VERSION="${{ env.IMAGE_VERSION }}" docker compose -f docker-compose.prod.yml up -d grpc-sample-server-prod

      - name: Cleanup unused Docker images
        run: docker image prune -af

      - name: List Docker images
        run: docker image ls

      - name: Remove tar file and List files in workspace
        run: |
          cd ${{ env.PATH_PROJECT }}
          rm ${{ env.IMAGE_NAME_TAR }} && ls -la

      - name: Check running containers
        run: docker ps -a
